version: "3.9"

services:
  db:
    image: postgres:13
    container_name: leadshunter-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finder_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: leadshunter-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leadshunter-web
    env_file:
      - .env.dev
    volumes:
      - .:/app
      - ./static:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    command: python manage.py runserver 0.0.0.0:8000

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leadshunter-celery
    env_file:
      - .env.dev
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    command: celery -A leadsHunter.celery_app worker --loglevel=info

volumes:
  postgres_data:
