services:
  db:
    image: postgres:13
    container_name: leadshunter-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finder_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: leadshunter-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leadshunter-web
    command: gunicorn leadsHunter.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
    expose:
      - "8000"
    depends_on:
      - db
      - rabbitmq
    restart: always

  nginx:
    image: nginx:alpine
    container_name: leadshunter-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    depends_on:
      - web
    restart: always

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leadshunter-celery
    command: celery -A leadsHunter.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    restart: always

volumes:
  postgres_data:
  static_volume:
