# Generated by Django 4.2.20 on 2025-04-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='radius_km',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
