# Generated by Django 4.2.20 on 2025-04-03 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_searchresult_city_searchresult_radius_km'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchresult',
            old_name='city',
            new_name='zona',
        ),
    ]
