# Generated by Django 4.2.20 on 2025-04-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_rename_city_searchresult_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='zona',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
