# Generated by Django 4.2.20 on 2025-04-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_place_zona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchResult',
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='place',
            name='radius_km',
            field=models.IntegerField(blank=True, null=True, verbose_name='Radio de búsqueda (km)'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='place',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='place',
            name='map_url',
            field=models.URLField(verbose_name='Enlace a Google Maps'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='place',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='place',
            name='query',
            field=models.CharField(max_length=255, verbose_name='Consulta original'),
        ),
        migrations.AlterField(
            model_name='place',
            name='social_media',
            field=models.TextField(blank=True, null=True, verbose_name='Redes Sociales'),
        ),
        migrations.AlterField(
            model_name='place',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web'),
        ),
        migrations.AlterField(
            model_name='place',
            name='zona',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zona o Ciudad'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('name', 'address'), name='unique_place_name_address'),
        ),
    ]
